### ISSUE TITLE
Research on creating world map

### ISSUE THREAD

**Issue by jessieqiu** [MSucharitha/TeamZombie#1]

**Comment by willhnguyen** [comment]
Update 10/26/2017
----
The terrain is partially completed. I think for the sake of this project, I'll entirely take and re-purpose Sebastian Lague's code instead of slowing going through the videos.

World boundaries have still not been implemented yet. That should be easy, though.

Tree/Natural Resource generation right now is crude and causes momentary spikes in computing power. I also need to remove them from the terrain the farther we get from it.

**Comment by willhnguyen** [comment]
Flat terrain with texture is completed.
